SELECT * FROM customer LIMIT 20;


SHOW COLUMNS FROM customer;

#Q1. WHAT IS THE TOTAL REVENUE GENERATED BY MALES VS FEMALES CUSTOMERS?

SELECT gender,SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

#Q2: WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied='Yes' AND purchase_amount >=(SELECT AVG(purchase_amount) FROM customer);

#Q3: WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING?
SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#Q4: COMPARE THE AVERAGE PURCHASE AMOUNT BETWEEN STANDARD AND EXPRESS SHIPPING?
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

#Q5: DO SUBSCRIBED CUSTOMERS SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE
#BETWEEN SUBSCRIBERS AND NON-SUBSCRIBERS?
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

#Q6: WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASE WITH DISCOUNT APPLIED?
SELECT item_purchased,
ROUND(100 *SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#Q7

WITH customer_type AS(
SELECT customer_id,previous_purchases,
CASE 
WHEN previous_purchases=1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer
)
SELECT customer_segment,COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

#Q8:

WITH item_counts AS(
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category,item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;

#Q9:
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10:

SELECT
	age_group,
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

WITH age_groups AS (
    SELECT
        NTILE(4) OVER (ORDER BY age) AS age_group,
        purchase_amount AS purchase_amount
    FROM customer
)
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM age_groups
GROUP BY age_group
ORDER BY age_group;



WITH age_groups AS (
    SELECT
        age,
        CASE NTILE(4) OVER (ORDER BY age)
            WHEN 1 THEN 'Young Adult'
            WHEN 2 THEN 'Adult'
            WHEN 3 THEN 'Middle-aged'
            WHEN 4 THEN 'Senior'
        END AS age_group,
        purchase_amount AS purchase_amount
    FROM customer
)
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM age_groups
GROUP BY age_group
ORDER BY total_revenue DESC;